### ISSUE TITLE
Unbound variable error

### ISSUE THREAD

**Issue by Jonny-G13** [aws/sagemaker-tensorflow-serving-container#101]
Hi there, I am attempting to build and push a docker image to my ECR in AWS from within a Sagemaker notebook instance but when I run the bash command: 

"!cd sagemaker-tensorflow-serving-container/ && ./scripts/build.sh --version 1.12 --arch cpu --region eu-west-2" 

I get the following error message:  

"scripts/shared.sh: line 28: AWS_DEFAULT_REGION: unbound variable" 

I find this strange because my default region in aws is set to "eu-west-2" and I am passing the argument to the script when I am running it. If you have any idea of why this is happening it would be a great help. Thanks in advance. 

Jonny

**Comment by nathanielrindlaub** [comment]
@Jonny-G13 - did you figure out a resolution to this? I'm getting the same error.

**Comment by Jonny-G13** [comment]
Yep, you just need to set the AWS_DEFAULT_REGION like so: 

"! cd sagemaker-tensorflow-serving-container; export AWS_DEFAULT_REGION=eu-west-2; ./scripts/start.sh --version 1.13 --arch cpu"

**Comment by nathanielrindlaub** [comment]
Got it. Thank you!
