### ISSUE TITLE
Sagemaker not finding inference.py after deployment

### ISSUE THREAD

**Issue by nathanielrindlaub** [aws/sagemaker-tensorflow-serving-container#122]
Hey there - I'm sure this is user error; I think I might be improperly structuring my model before zipping and deploying it to Sagemaker, but I have scoured the docs and issues here and can't find a clear example of what I'm trying to do to replicate. I have a TF model I'd like to deploy as a Sagemaker endpoint, and right now I'm attempting to do so with a Sagemaker notebook instance and the Sagemaker Python SDK. I also have an ```inference.py``` script and a ```requirements.txt``` I'd love to pass into the serving container as well to do pre/post processing.

As [described in this blog post](https://aws.amazon.com/blogs/machine-learning/deploy-trained-keras-or-tensorflow-models-using-amazon-sagemaker/), I uploaded my model to the notebook instance with the following directory structure:

```
>>> notebook/
>>>      ├─ deploy.ipynb
>>>      ├─ export
>>>            └─ Servo
>>>                  └─ 1
>>>                        └─ saved_model.pb
>>>                        └─ variables
>>>            └─ code
>>>                  └─ inference.py
>>>                  └─ requirements.txt
```

zipped and uploaded it to s3: 
```python
import tarfile
import sagemaker
with tarfile.open('model.tar.gz', mode='w:gz') as archive:
    archive.add('export', recursive=True)
sagemaker_session = sagemaker.Session()
inputs = sagemaker_session.upload_data(path='model.tar.gz', key_prefix='model')
```

And deployed it to Sagemaker:
```python
from sagemaker.tensorflow.model import TensorFlowModel

sagemaker_model = TensorFlowModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz',
                                  role = role,
                                  framework_version = '1.12',
                                  entry_point = 'inference.py',
                                  source_dir = 'export/code')

predictor = sagemaker_model.deploy(initial_instance_count=1,
                                   instance_type='ml.m4.xlarge',
                                  )
```

The model deploys just fine but when I try to submit requests to it, I get errors, and there is no indication in the CloudWatch logs that the ```input_handler``` function in ```inference.py``` is firing or that the dependencies in requirements.txt are being installed. In contrast, when I successfully load models with ```code/requirements.txt``` into a sagemaker-tensorflow-serving-container running on my local computer, I get output indicating that it's loading the dependencies in the ```log.txt``` and log commands from within inference.py are printed out:

```
INFO:__main__:installing packages from requirements.txt...
...
INFO:inference:input_handler firing
```

I haven't seen anything like that in my CloudWatch logs, leading me to think I'm either not structuring the zipped directories correctly or not using ```entry_point``` or ```source_dir``` correctly.

Any advice would be much appreciated!

**Comment by laurenyu** [comment]
sorry for the slow response here.

for reference, here are the docs on the directory structure: https://github.com/aws/sagemaker-tensorflow-serving-container/#prepost-processing

It looks like you're using the wrong TensorFlow serving class. Can you try using `sagemaker.tensorflow.serving.Model` instead? ([docs](https://sagemaker.readthedocs.io/en/stable/sagemaker.tensorflow.html#tensorflow-serving-model))

**Comment by nathanielrindlaub** [comment]
That was it. Thank you @laurenyu!
