### ISSUE TITLE
Request: EIA support for tensorflow 2.1

### ISSUE THREAD

**Issue by szabadaba** [aws/sagemaker-tensorflow-serving-container#127]
Are there any plans to create EIA images for tensorflow 2 versions? It looks like 1.14 was the last version with an EIA image created. Using EIA for sagemaker serving is compelling from a price/performance perspective.

**Comment by desmanda** [comment]
is there any plans to support this request, me and my Team also looking forward to having this feature

**Comment by laurenyu** [comment]
sorry for the lack of response here. can you please open an issue in https://github.com/aws/deep-learning-containers?
