### ISSUE TITLE
ModelError ... InvokeEndpoint 500 ... "{"error": "No module named 'sklearn.externals.joblib'"}"

### ISSUE THREAD

**Issue by petervandenabeele** [aws/sagemaker-tensorflow-serving-container#135]
When the the `inference.py` code uses `import joblib` and the `requirements.txt` file does not pin the version of scikit-learn to less then 0.23.0, then since 12 May 2020, with version 0.23.0 this may fail with :

```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "{"error": "No module named 'sklearn.externals.joblib'"}".
```
It is not entirely clear to me where scikit-learn is involved, since this is a tensorflow serving container.

In any case, for other people hitting this error, a possible work-around is to pin the version of scikit-learn in the requirements.txt to:
```
scikit-learn==0.22.0
```

**Comment by ChuyangDeng** [comment]
Hi @petervandenabeele , could you provide a list of dependencies that you are installing with ``requirements.txt`` as well as the container version and device type? I cannot reproduce it with only including ``joblib`` in ``requirements.txt`` and import it on a SageMaker tensorflow serving 2.0 cpu container

**Comment by petervandenabeele** [comment]
Thx @ChuyangDeng for your research.

I am using an model.tar.gz, which is a tar from this directory structure:
```
$ find export/
export/
export/Servo
export/Servo/code
export/Servo/code/requirements.txt
export/Servo/code/inference.py
export/Servo/code/<file>.save
export/Servo/1
export/Servo/1/saved_model.pb
export/Servo/1/variables
export/Servo/1/variables/variables.data-00000-of-00001
export/Servo/1/variables/variables.index
```

The inference.py code (proprietary), started with code like:

```
import json
import joblib
import logging
import numpy as np
import pandas as pd
import scipy
import time

...

# this line below breaks with the reported error
# it is the only time `joblib` is used in the code
# I think this is called from the output_handler
joblib.load('<file>.save')
```

OLD VERSION
* this version of requirements.txt "worked" until Monday 11 May 2020 and then started breaking (while creating and using the newly created endpoint from exactly the same model.tar.gz) since 13 May 2020
* the requirements.txt in the old model.tar.gz was:
```
joblib==0.14.1
numpy==1.18.1
pandas==0.25.3
sklearn==0.0
```

NEW VERSION:

* in this requirements.txt, I forced the version of `scikit-learn` to be < 0.23.0 and kept all the rest the same and this also works on 14 May 2020. I presume there may be a deprecation warning about sklearn.externals.joblib , but I am not sure:

```
joblib==0.14.1
numpy==1.18.4
pandas==0.25.3
pip==20.1
scikit-learn==0.22.0
scipy==1.4.1
```

The application code and all the rest of the code or configuration settings was unchanged.

What I find strange, is that I _do_ call `import joblib` directly in the code, I do NOT call
`import sklearn.externals.joblib` myself.

Aha, now that I looked, I do see that the "<file>.save", while a "binary" file, does contain strings that look like this:

```
sklearn.preprocessing.data
MinMaxScaler
sklearn.externals.joblib.numpy_pickle
...
sklearn_version ... 0.20.3
```

So maybe it is really related to the handling of this "<file>.save" from our application, and not really the TensorFlow Serving container ?

Hope This helps, thanks again for your investigation.

**Comment by petervandenabeele** [comment]
Turns out this was a problem in the <file>.save that still relied on the old `scikit-learn` version.

Closing this. Thanks for your investigation.
