### ISSUE TITLE
Are Deep Learning Containers the same as TF Serving Containers?

### ISSUE THREAD

**Issue by nlothian** [aws/sagemaker-tensorflow-serving-container#136]
https://aws.amazon.com/releasenotes/available-deep-learning-containers-images/ has a list of containers which seems to be partially the same as the list in this repo, but more recent (has TF2.2 for example).

However the images are in a different format. Is that page intended to be a replacement for this? 

If so, (some?) don't seem to be deployed to `ap-southeast-2`. 

I tried building using `763104351884.dkr.ecr.ap-southeast-2.amazonaws.com/tensorflow-inference:2.2.0-gpu-py37-cu101-ubuntu18.04` and it failed.

**Comment by nadiaya** [comment]
TF Serving is a Deep Learning Container and the documentation you linked is correct.

You get an error because TF2.2 is supported only for training and for inference.

And TF Serving 2.2 is not available yet: https://pypi.org/project/tensorflow-serving-api/

**Comment by nlothian** [comment]
Thanks @nadiaya - perhaps it would be possible to put a note about that at the top of `README.md` for this project. Or anywhere really? 

The current experience involves trying to work out what the current project is by comparing commit dates in githib repo with press release announcement dates and guessing they maybe the same things.
