### ISSUE TITLE
how to load tokenizer when deploying a keras text classification model

### ISSUE THREAD

**Issue by vinayakkailas** [aws/sagemaker-tensorflow-serving-container#141]
I have a text classifier model trained on keras. I converted the model to tf serving format and successfully created the endpoint. Now i am trying to add a preprocessing and post processing function as an entry script, but i am confused where to keep my tokenizer pickle file. I have tried keeping it in the same directory where entry point script is present, but the system is unable to identify the file. Some one please let me know how to where to keep this file so that i can load it in my entry point script

**Comment by ChuyangDeng** [comment]
Hi @vinayakkailas,

Am I understanding it correctly that you are trying to use the pickle file in your pre/post-processing script `inference.py` but got FileNotFound error?

If so, where did you put your pickle file? When your model is downloaded to SageMaker TFS container, it will be put in `/opt/ml/mode` and the structure of the model might be:

/opt/ml/model
    model_name
        |--[model_version_number]
            |--variables
            |--saved_model.pb
            |--<pickle file?>
    code
        |--inference.py

Depending on where you put your pickle file and how were you using SageMaker TensorFlor Estimator and Model objects, your model might be repacked and the pickle file is removed (https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L546) if your pickle file was in the `code_dir` when training but not put into the `source_dir` when serving.

You could bash into the container, and check if your pickle file is present under `/opt/ml/model` directory.

**Comment by vinayakkailas** [comment]
Hi @ChuyangDeng 

I added path /opt/ml/model/code/ while loading, now i am able to load successfully. I had kept the pickle file along with entry point script in source_dir itself. 

I used tokenizer = pickle.load(open('/opt/ml/model/code/tokenizer.pickle', 'rb'))

Thanks for response
