### ISSUE TITLE
Does the underlying code of the container is wrote by C++

### ISSUE THREAD

**Issue by Ageneinair** [aws/sagemaker-tensorflow-serving-container#143]
Is this project for realizing the same function as the [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving), but use a different way? Or just bring the [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving) to AWS?

I have this question because I saw some underlying core code is written in python like this one:
https://raw.githubusercontent.com/aws/aws-deep-learning-containers-utils/master/deep_learning_container.py, but as I know the whole structure of [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving) is written in C++

**Comment by laurenyu** [comment]
This repository is for bringing TFS support to Amazon SageMaker.

For what versions of TFS are supported, see https://aws.amazon.com/releasenotes/available-deep-learning-containers-images.

The code is used to build Docker images, whose Dockerfiles can be found at https://github.com/aws/deep-learning-containers/tree/master/tensorflow/inference/docker.

**Comment by Ageneinair** [comment]
I saw all the code based on
```
TFS_URL=https://tensorflow-aws.s3-us-west-2.amazonaws.com/2.1/Serving/CPU-WITH-MKL/tensorflow_model_server
```
But I can't get access to this one, is this one written by C++?

**Comment by laurenyu** [comment]
Yes, it's basically the same. Since it's installed by the Dockerfiles now stored in https://github.com/aws/deep-learning-containers, I would suggest opening an issue in that repo for further questions.
