### ISSUE TITLE
Does handler function occupy the compute resource of the container?

### ISSUE THREAD

**Issue by Ageneinair** [aws/sagemaker-tensorflow-serving-container#144]
If we have lots of requests to the container at the same time, we'll have a queue for those requests, and the container will inference them one by one. But if we add a handler function for the container, does this handler function will take the container's compute resource, which makes the whole inference time longer? or it's just the same as the one without the handler function?

**Comment by metrizable** [comment]
@Ageneinair , thanks for filing the issue. I believe you're asking whether invocation latency and compute load will be affected by implementations [in the handler](https://github.com/aws/sagemaker-tensorflow-serving-container#prepost-processing)? The answer is yes, and will vary according to the handler's implementation and payload size.

**Comment by Ageneinair** [comment]
Okay, thank you!
