### ISSUE TITLE
How to use a new model to replace the previous one?

### ISSUE THREAD

**Issue by Ageneinair** [aws/sagemaker-tensorflow-serving-container#145]
After we upload the model to S3 and create an endpoint for it, how we can update the model for the endpoint?

**Comment by metrizable** [comment]
From [here](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-hosting.html):

> Changing or deleting model artifacts or changing inference code after deploying a model produces unpredictable results. If you need to change or delete model artifacts or change inference code, modify the endpoint by providing a new endpoint configuration. Once you provide the new endpoint configuration, you can change or delete the model artifacts corresponding to the old endpoint configuration.

Let me know if that's what you were looking for.

**Comment by Ageneinair** [comment]
Got it, ty!
