### ISSUE TITLE
Install other apt lib for serving container.

### ISSUE THREAD

**Issue by jason9075** [aws/sagemaker-tensorflow-serving-container#161]
**Describe the feature you'd like**
Hi, I am using ```inference.py``` to use pre-processing, and I put opencv-python in requirement.txt. But when I deploy the container, it show up an error ```ImportError: libGL.so.1: cannot open shared object file: No such file or directory```. 
I need to install some apt library ```libgl1-mesa-glx``` in container to fix this.

**Comment by SergTogul** [comment]
Jason, could you add some colors to it?
Which container do you use? 
How do you run the container? 

Were you able to install the library? Did everything work after it? You can find instructions how to customize a container [here](https://github.com/aws/deep-learning-containers/blob/master/custom_images.md).
I believe the only thing you need to add into docker file is 
`RUN sudo apt update && sudo apt install libgl1-mesa-glx`

**Comment by jason9075** [comment]
Thanks !
