### ISSUE TITLE
Multi Model Serving for Tensorflow 2.3.0

### ISSUE THREAD

**Issue by abhi1793** [aws/sagemaker-tensorflow-serving-container#169]
Are you planning for adding a container for Tensorflow 2.3.0?

**Comment by metrizable** [comment]
Hello @abhi1793 

Thank you for using SageMaker. Have you looked into the [available](https://aws.amazon.com/releasenotes/available-deep-learning-containers-images/) [deep-learning-containers](https://github.com/aws/deep-learning-containers/tree/master/tensorflow/inference/docker/2.3.0/py3)? They come with the SageMaker Inference Toolkits and are maintained for all recent versions of TensorFlow.

**Comment by abhi1793** [comment]
@metrizable Thanks for replying back. I was able to come across the mentioned repo yesterday and start my work as the dockers available have multi-model serving capabilities. Thanks a lot 👍
