### ISSUE TITLE
Container timing out with large batched CSV payloads

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-tensorflow-serving-container#18]
From https://github.com/aws/sagemaker-python-sdk/issues/703, a user sending 3.7MB of CSV to the Tensorflow Serving container sees timeouts:

`2019/03/17 12:34:14 [info] 67#67: *11 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080`

`2019-03-17T12:34:14.387:[sagemaker logs]: sagemaker-us-east-1-668139184987/batch_transform_demo/test_data_100k.csv: Unable to get response from algorithm`

I've reproduced this with a ~250KB payload with 30000 lines.

**Comment by jesterhazy** [comment]
closing, since the fix was released in https://github.com/aws/sagemaker-tensorflow-serving-container/releases/tag/v1.1.4
