### ISSUE TITLE
CSV parses single-line inputs as individual scalars, not one example.

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-tensorflow-serving-container#20]
Inspired by https://github.com/aws/sagemaker-python-sdk/issues/703

As far as I can tell, this behavior for CSV isn't right:

https://github.com/aws/sagemaker-tensorflow-serving-container/blob/227a1c0383938dc6ccc42704cce1c51018c30b7b/container/sagemaker/tensorflow-serving.js#L176-L180
Without the outer list for a single example, a single row with N CSV values is treated as a list of N scalars rather than as one example with N dimensions.

But it looks like this behavior is expected:

https://github.com/aws/sagemaker-tensorflow-serving-container/blob/227a1c0383938dc6ccc42704cce1c51018c30b7b/test/integration/local/test_container.py#L132-L135

Wouldn't it make more sense for the input to be `1.0\n2.0\n5.0` in this case, and for the TFS serving container to turn "1.0, 2.0, 5.0" into

`{"instances":[[1.0, 2.0, 5.0]]}`

instead? Is there some other way to predict on a single row of CSV with multiple features?

**Comment by jesterhazy** [comment]
closing, since the fix was released in https://github.com/aws/sagemaker-tensorflow-serving-container/releases/tag/v1.1.4
