### ISSUE TITLE
Documentation: eia option for tensorflow-serving container images

### ISSUE THREAD

**Issue by sboshin** [aws/sagemaker-tensorflow-serving-container#38]
520713654638.dkr.ecr.{REGION}.amazonaws.com/sagemaker-tensorflow-serving:{TENSORFLOW_SERVING_VERSION}-{cpu|gpu}

should be

520713654638.dkr.ecr.{REGION}.amazonaws.com/sagemaker-tensorflow-serving:{TENSORFLOW_SERVING_VERSION}-{cpu|gpu|eia}

**Comment by jesterhazy** [comment]
fixed by #39
