### ISSUE TITLE
Missing 1.13/Dockerfile.eia

### ISSUE THREAD

**Issue by pnpnpn** [aws/sagemaker-tensorflow-serving-container#54]
I tried running `./scripts/build.sh --version 1.13 --arch eia`. It fails because of missing `docker/1.13/Dockerfile.eia`

**Comment by jesterhazy** [comment]
@pnpnpn thanks for using SageMaker!

The `.eia` docker file is missing because Elastic Inference doesn't support Tensorflow Serving 1.13 yet. The EI team is working on this, so keep checking back.

**Comment by jesterhazy** [comment]
Update: we have a PR open for EI 1.13 support: https://github.com/aws/sagemaker-tensorflow-serving-container/pull/55
