### ISSUE TITLE
Need support for tensorflow 1.14

### ISSUE THREAD

**Issue by panfeng-hover** [aws/sagemaker-tensorflow-serving-container#63]
Hello, I am wondering when will the sagemaker endpoint docker image support tensorflow 1.14. Thanks!

**Comment by icywang86rui** [comment]
@panfeng-hover 
We are currently working on releasing TensorFlow and TensorFlow Serving 1.14 docker images. Sorry that i won't be able to give you an estimate but it will happen in the near future. Closing the issue for now. Feel free to reopen if you any more questions.
