### ISSUE TITLE
The following error was encountered while trying to retrieve the URL:http://localhost:8080/invocations 

### ISSUE THREAD

**Issue by VyBui** [aws/sagemaker-tensorflow-serving-container#7]
Hello,

I was following the tutorials in README.md file. Everything is fine until run the command:
`./scripts/curl.sh`. It returns the page with message like this:

"The following error was encountered while trying to retrieve the URL: <a href="http://localhost:8080/invocations">http://localhost:8080/invocations</a> 

Please see pictures for more information!

I ran the code in Amazon RedHat Linux 7.3 but I was able to run this folder in my Ubuntu 18.04. Has any one has faced this problem before. Please let's me know what to do next?

![screenshot-user-images githubusercontent com-2019 02 19-14-12-08](https://user-images.githubusercontent.com/15938335/52996557-8e3e8200-3450-11e9-9a45-8a5bc355e217.png)
![screenshot-github com-2019 02 19-14-13-01](https://user-images.githubusercontent.com/15938335/52996560-8ed71880-3450-11e9-8ab7-1779f873d1f4.png)

**Comment by VyBui** [comment]
I guess there is something to do with the AWS settings.

**Comment by jesterhazy** [comment]
These aren't error messages generated by our container code. It looks like your `curl` request is being routed through a proxy server of some kind, and that proxy server can't reach `localhost`. Check your system's proxy settings to disable that and try again.

**Comment by VyBui** [comment]
hey @jesterhazy I am able to run the command by unset http_proxy for the curl request.

Thank you for your response!
