### ISSUE TITLE
How to make GRPC predict request from handler()

### ISSUE THREAD

**Issue by rhosseini** [aws/sagemaker-tensorflow-serving-container#72]
I have to send a specific type of request to the model and, according to the GitHub, I have to use handler() instead of input_handler() and output_handler(). I could find many examples that explain how to send predict request to the model using REST API. How can I make GRPC predict request from the handler()? any example that I could follow?

Thanks!

**Comment by ChuyangDeng** [comment]
Hi @rhosseini, thanks for using SageMaker!

The pre/post-processing allows you to customize your inference calls, for REST API calls, you only need to sent the request through `requests.post(...)`, if you want to make GRPC inference request, you need to set up a channel, use GRPC pb2 messages to communicate with the GRPC server in the `handler()` function:

```
import grpc
from tensorflow_serving.apis import get_model_status_pb2
from tensorflow_serving.apis import inference_pb2
from tensorflow_serving.apis import model_service_pb2_grpc
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc

# GRPC request, you may want to use specific signature or different input format, dimensions, etc
# here's tensorflow serving's code:
# https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto
request = predict_pb2.PredictRequest()
request.model_spec.name = your-model-name

# you can pre-process your input before this
request.inputs['x'].float_val.append(1.0) 

# set up channel and send request
channel = grpc.insecure_channerl(context.grpc_uri)
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

# you can post-process after getting the result
result = stub.Predict(request)
```

**Comment by rhosseini** [comment]
Hi  @ChuyangDeng:

Thank you so much for your answer.

**Comment by mycaule** [comment]
Hello,
has anyone been able to solve that problem and if possible can provide a working code sample?

Thanks a lot.

**Comment by yixu34** [comment]
Hey @mycaule, not sure if you've already figured this out, but here's what worked for me. It's similar to what @ChuyangDeng [posted earlier](https://github.com/aws/sagemaker-tensorflow-serving-container/issues/72#issuecomment-523605025). I'm using tensorflow version `1.14.0`.

```python3
import grpc

from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc

MAX_GRPC_MESSAGE_LENGTH = 512 * 1024 * 1024

def handler(data, context):
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'model'
    request.model_spec.signature_name = 'serving_default'
    request.inputs['x'].float_val.append(1.0) 

    options = [
        ('grpc.max_send_message_length', MAX_GRPC_MESSAGE_LENGTH),
        ('grpc.max_receive_message_length', MAX_GRPC_MESSAGE_LENGTH)
    ]
    channel = grpc.insecure_channel(f'0.0.0.0:{context.grpc_port}', options=options)
    stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)
    result = stub.Predict(request, 10.0)
```
In other words, the key is that it's now `context.grpc_port`, running on loopback. Also you'll want `max_send_message_length` and `max_receive_message_length` - I saw some example somewhere that used `max_message_length`, but that doesn't seem to be correct anymore.

**Comment by mycaule** [comment]
@cenkbircanoglu
