### ISSUE TITLE
Request: tensorflow 1.14 docker container

### ISSUE THREAD

**Issue by psaks** [aws/sagemaker-tensorflow-serving-container#74]
Any reason there is not a 1.14 docker container?

**Comment by surajkota** [comment]
If you are looking for pre-built container for TensorFlow-1.14, they have been released and can be used from the SDK. You can also pull it manually: `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference::1.14-gpu`. Image is available in other regions as well

If you are looking for the dockerfile, you can find it here - https://github.com/aws/sagemaker-tensorflow-serving-container/tree/asimov/docker/1.14. 

These images will be merged with changes on master soon

Thanks

**Comment by psaks** [comment]
Thanks @surajkota, 
I successfully used `763104351884.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tensorflow-serving:1.13-cpu` which also worked for 1.11 and 1.12, but failed for 1.14. Would be good if someone from AWS could update the images a bit quicker - the tensorflow/serving 1.14.0 was last updated 2 month ago on docker hub. I know this one is a minor upgrade, but 2.0 should be coming up soon. 
Thanks again

**Comment by surajkota** [comment]
Hi psaka@, 

Tensorflow-serving 1.14 images have been released for sagemaker as well. There has been a change in the ECR repositories starting 1.13 and hence the old URIs(`sagemaker-tensorflow-serving`) dont work for 1.14. Could you please try one of the following images: 

For CPU:
`763104351884.dkr.ecr.eu-central-1.amazonaws.com/tensorflow-inference:1.14-cpu`

For GPU:
`763104351884.dkr.ecr.eu-central-1.amazonaws.com/tensorflow-inference:1.14-gpu`

Let us know if you have any issues.

Refer to the documentation for further information: https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

Thanks

**Comment by psaks** [comment]
Many thanks @surajkota - that worked!

**Comment by prameshbajra** [comment]
@surajkota @psaks Hello, 
I know this is not a good place to ask this but I am stuck for quite a time and I see no other solution.

Were you guys able to run your inference on a GPU? My endpoint is not using GPU it seems.
(For more info please have a look at this: https://stackoverflow.com/questions/59421569/sagemaker-not-using-gpu-even-though-it-is-deployed-in-gpu-instance)

Thanks.
