### ISSUE TITLE
MKL - DNN Support

### ISSUE THREAD

**Issue by gautiese** [aws/sagemaker-tensorflow-serving-container#94]
Reference: 0420648209

I want to deplow a model which consumes images in NCHW format.
This can only be done on CPU instances where TF has been compiled with MKL-DNN support.

Can you please provide containers with MKL - DNN support?

**Comment by ChoiByungWook** [comment]
Reference: 0420648209

**Comment by surajkota** [comment]
Hi @gautiese, latest tensorflow version -1.15 and 2.0 have been complied with MKL support.

Earlier versions of tensorflow-1.13, 1.14 were also released with MKL support
