### ISSUE TITLE
update readme instructions to reflect new ecr image naming conventions

### ISSUE THREAD

**Issue by RZachLamberty** [aws/sagemaker-tensorflow-serving-container#97]
I just burned a few hours trying to get my 1.14 version model to work in version 1.12 because I thought (based on your readme) that only versions up to 1.12 are supported.

then I found [this comment](https://github.com/aws/sagemaker-tensorflow-serving-container/issues/74#issuecomment-528528555) on a since-closed issue which mentioned that a 1.14 version *does* exist, but is at a different url. this information should be put into the `README`

**Comment by yuanzhua** [comment]
Hi RZachLamberty,

Apologize that the readme is not update to date. We will update the doc ASAP. For Tensorflow, we support up to v1.15 and v2.0 now. May I know which section of readme mention that "only versions up to 1.12 are supported"? We'd like to make sure our doc update will cover these.

**Comment by RZachLamberty** [comment]
the only place I found info about the containers was in the `README`, in the [Creating a Sagemaker Model section](https://github.com/aws/sagemaker-tensorflow-serving-container#creating-a-sagemaker-model). there it is written:

> Where REGION is your AWS region, such as "us-east-1" or "eu-west-1"; TENSORFLOW_SERVING_VERSION is one of the supported versions: "1.11" or "1.12"; and "gpu" for use on GPU-based instance types like ml.p3.2xlarge, or "cpu" for use on CPU-based instances like ml.c5.xlarge.

not only are the `ecr` urls being referrenced there outdated, the version information is clearly wrong. it would be nice if the table were kept up to date of course, or if you could link to the place in `aws` that is

**Comment by laurenyu** [comment]
looks like this was addressed in #99
